- name: Configure nginx for the app
  template: src=go-app.conf.j2 dest=/etc/supervisor/conf.d/{{app_name}}.conf group=www-data owner=www-data force=yes

- name: Deploy directory is present
  file: state=directory path={{deploy_directory}}

- name: Deploy go app
  copy: src={{binary_local_path}}/{{app_name}} dest={{deploy_directory}}/{{app_name}} owner={{deploy_user}} group={{deploy_user}} mode="u+x,g+x,o+x"

- name: Copy go app configs
  copy: src={{binary_local_path}}/conf dest={{deploy_directory}} owner={{deploy_user}} group={{deploy_user}}

- name: Start go app
  supervisorctl: name={{app_name}} state=started config=/etc/supervisor/conf.d/{{app_name}}.conf